# This workflow packages up the ecl-builder package and publishes it to NPM.

name: Publish NPM package

on:
  release:
    types: [ published ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: npm
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
        node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
